services:
  paaaaath:
    image: python:3.8
    volumes:
      - ./:/paaaaath:cached
    working_dir: /paaaaath
    depends_on:
      - gcs
    command: sh -c "pip install poetry && poetry install && poetry run wait-for-it -s gcs:4443 -- pytest"
  gcs:
    image: fsouza/fake-gcs-server
