# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: run unit tests
        shell: bash
        run: |
          docker-compose up -d s3
          docker-compose up -d gcs
          docker-compose run test${PYTOHN_VERSION}
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
