name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Set up poetry
        run: |
          curl -sSL https://install.python-poetry.org | python
          poetry self add "poetry-dynamic-versioning[plugin]"
      - name: Publish package
        run: |
          poetry publish --username=ar90n --password=${PYPI_PASSWORD} -n --build
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
