name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Publish package
        run: |
          pip install poetry
          poetry publish -u ar90n -p ${PYPI_PASSOWRD} -n --build
        env:
          PYPI_PASSOWRD: ${{ secrets.PYPI_PASSWORD }}

